version: "3.3"

services:
    ms-otp:
        build: .
        # ports: 
        #     - "7000:7000"
        # container_name: ms-user
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=authme
            - DB_USER=root
            - DB_PASSWORD=mariposa
            - JWT_SECRET_KEY = 'clave-secreta-de-la-app'
            - JWT_ACCESS_TOKEN_EXPIRES = 3600

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ms-user.rule=Host(`ms-user.authme.localhost`)"
            - "traefik.http.routers.ms-otp.tls=true"
            - "traefik.http.services.ms-otp.loadbalancer.server.port=5000"
            - "traefik.http.middlewares.ms-otp-circuitbreaker.circuitbreaker.expression=NetworkErrorRatio() > 0.5"
            - "traefik.http.routers.ms-otp.middlewares=ms-otp-circuitbreaker"
            - "traefik.docker.network=red"
            
        volumes:
            - ./main:/app/main
            - ./app.py:/app/app.py

        networks:
            - traefik-network

networks:
    traefik-network:
        external: true